// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcFKBiOvKnqU2BWm5UojSI-ySK3_lugkI',
    appId: '1:673666568974:web:597db5a8f7a29048537d5f',
    messagingSenderId: '673666568974',
    projectId: 'rtinventory-47f96',
    authDomain: 'rtinventory-47f96.firebaseapp.com',
    storageBucket: 'rtinventory-47f96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIITH6hbFjnzugFYwGYep9ww_AJpeR2vM',
    appId: '1:673666568974:android:fb9719aa787b7a32537d5f',
    messagingSenderId: '673666568974',
    projectId: 'rtinventory-47f96',
    storageBucket: 'rtinventory-47f96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS8BuW0YMSbIHIGwOMrJcZUqzYTuBbj5o',
    appId: '1:673666568974:ios:de44caac44394243537d5f',
    messagingSenderId: '673666568974',
    projectId: 'rtinventory-47f96',
    storageBucket: 'rtinventory-47f96.firebasestorage.app',
    iosBundleId: 'com.reiworks.arteaInventoryApp',
  );
}
